$(document).ready(function()
{
    $('#form-submit').click(function()
    {
        $.ajax
        ({
            url:"./index.html",
            type:"POST",
            cashe:false,
            async:true,
            data:{ 
                name:$('#name').val(), 
                email:$('#email').val(),
                message:$('#message').val(),
            },
            /*
            success: function(data) {
                $('#').html(data);
            }*/
        })
    });
});